name: Bug 🐞
description: Report an issue to help us improve the project.
title: "[Bug] <write a small description here>"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the issue or bug you are facing, also include what you tried and what didn't work.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable.
    validations:
      required: false

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked the existing issues."
          required: true

        - label: "I follow [Contributing Guidelines](https://github.com/Aryainguz/Euphoria-Check-PERMA-Meter-Express/blob/main/CONTRIBUTING.md) of this project."
          required: true