name: Style Changing Request 👯‍♂️
description: Suggest a style design
title: '[Style]'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this template!
  - type: textarea
    id: style-idea
    attributes:
      label: What's the style idea?
      placeholder: Add descriptions
      value: 'We need to improve'

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked the existing issues."
          required: true

        - label: "I follow [Contributing Guidelines](https://github.com/Aryainguz/Euphoria-Check-PERMA-Meter-Express/blob/main/CONTRIBUTING.md) of this project."
          required: true